Updates workflows to use orgflow-actions/*

diff --git a/.github/workflows/all-env-flowin.yml b/.github/workflows/all-env-flowin.yml
--- a/.github/workflows/all-env-flowin.yml
+++ b/.github/workflows/all-env-flowin.yml
@@ -1,105 +1,72 @@
-# Flow in all environments (pull the metadata from Salesforce into Git).
+# Flow in all environments in stack (sync metadata from Salesforce into Git)
+
 # This workflow consists of two jobs:
-# - The first runs `orgflow env:list` and transforms the output into a matrix for GitHub actions.
-# - The second uses the matrix created in the first step to tun `orgflow env:flowin` for all the environments.
+# - The first runs 'orgflow env:list' and transforms the output into a matrix
+# - The second uses the matrix created in the first step to run 'orgflow env:flowin' for each environment
 
 name: Flow in all environments
+
 on:
   schedule:
-    - cron:  '0 1 * * *' # Runs nightly at 1am.
+    - cron: "0 1 * * *" # Runs nightly at 01:00 UTC.
   workflow_dispatch: # Can also be manually triggered, if needed.
-
-# The env:flowin command needs to be able to push changes back to the repo.
-permissions:
-  contents: write  
 
 jobs:
   create-matrix:
-    name: "Get Environments"
-    runs-on: ubuntu-latest    
-    container: 
-      image: orgflow/cli:latest
-    env:
-      ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.
-      ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}      
-      ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }}
+    name: List environments
+    runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
-    steps:
-    # Use jq to transform the output from env:list into the format expected for a matrix strategy:
-    - id: set-matrix
-      run: echo "::set-output name=matrix::`orgflow env:list --output=json | jq '[.[] | .name]' -c`"
-      
-  flow-in:
-    name: "Flow In Environment"
-    needs: create-matrix
-    runs-on: ubuntu-latest    
-    container: 
-      image: orgflow/cli-private:latest
-      credentials:
-        username: paynecrl97
-        password: ${{ secrets.DOCKERHUB_PASSWORD }}  
-    env:
-      ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.
-      ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}      
-      ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }}   
-      SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
-      SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }} 
-    strategy:
-      fail-fast: false # If one environment fails, don't allow GitHub to cancel the jobs for all the rest. 
-      matrix: 
-        environmentName: ${{fromJson(needs.create-matrix.outputs.matrix)}}
-          
-    steps:
-      # Verify input:
-      - name: Verify stack name
-        id: verifyStackName
-        if: ${{ always() && env.ORGFLOW_STACKNAME == '' }}
-        run: |
-          echo 'Repository secret ORGFLOW_STACKNAME has not been set. See the readme for more details.'
-          exit 1
-      - name: Verify license key
-        id: verifyLicenseKey
-        if: ${{ always() && env.ORGFLOW_LICENSEKEY == '' }}
-        run: |
-          echo 'Repository secret ORGFLOW_LICENSEKEY has not been set. See the readme for more details.'
-          exit 1
-      - name: Verify Salesforce username
-        id: verifySalesforceUsername
-        if: ${{always() && env.SALESFORCE_USERNAME == '' }}
-        run: |
-          echo 'Repository secret SALESFORCE_USERNAME has not been set. See the readme for more details.'
-          exit 1
-      - name: Verify Salesforce password
-        id: verifySalesforcePassword
-        if: ${{always() && env.SALESFORCE_PASSWORD == '' }}
-        run: |
-          echo 'Repository secret SALESFORCE_PASSWORD has not been set. See the readme for more details.'
-          exit 1
-          
-      # Configure Git:
-      - uses: orgflow-actions/configure-git@v0.4
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
 
-      # Configure auth:
-      - uses: orgflow-actions/set-salesforce-auth@v0.2
-        with:
-          username: ${{ secrets.SALESFORCE_USERNAME }}
-          password: ${{ secrets.SALESFORCE_PASSWORD }}        
-          
-      # Run OrgFlow command:
-      - name: env:flowin
+    steps:
+      # Verify secrets:
+      - name: Verify secrets
         run: |
-          orgflow env:flowin -e="${{ matrix.environmentName }}"
-      
-      # Publish diagnostic bundles to artifacts (if any):
-      - name: Publish diagnostic bundle as artifact
-        uses: actions/upload-artifact@v2
-        if: always()
+          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.SALESFORCE_USERNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_USERNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.SALESFORCE_PASSWORD }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_PASSWORD has not been set. See the Readme for more details." && exit 1; fi;
+
+      # Install and configure OrgFlow:
+      - name: Install OrgFlow
+        uses: orgflow-actions/setup@v1
         with:
-          name: Diagnostic Bundles
-          path: |
-            /tmp/OrgFlow_Diagnostics_*.zip
-          retention-days: 3
-          if-no-files-found: ignore
+          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
+          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
+        env:
+          ORGFLOW_ACCEPTEULA: "true"
+
+      # Use jq to transform the output from env:list into the format expected for a matrix strategy:
+      - name: Create matrix
+        id: set-matrix
+        run: echo "::set-output name=matrix::`orgflow env:list --output=json | jq '[.[] | .name]' -c`"
+
+  env-flowin:
+    name: Flow in environment
+    needs: create-matrix
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false # Even if an environment fails, do the rest
+      matrix:
+        environmentName: ${{ fromJson(needs.create-matrix.outputs.matrix) }}
+
+    steps:
+      # Install and configure OrgFlow:
+      - name: Install OrgFlow
+        uses: orgflow-actions/setup@v1
+        with:
+          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
+          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
+          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
+          git-username: ${{ github.actor }}
+          git-password: ${{ secrets.GITHUB_TOKEN }}
+          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
+          # Ensure artifact names are unique:
+          diag-artifact-name: orgflow_diag_${{ github.job }}_${{ matrix.environmentName }}_${{ github.run_attempt }}
+        env:
+          ORGFLOW_ACCEPTEULA: "true"
+
+      # Run OrgFlow command:
+      - name: Run env:flowin
+        run: |
+          orgflow env:flowin --environment="${{ matrix.environmentName }}"
diff --git a/.github/workflows/env-flowin.yml b/.github/workflows/env-flowin.yml
--- a/.github/workflows/env-flowin.yml
+++ b/.github/workflows/env-flowin.yml
@@ -1,88 +1,46 @@
-# Flow in an environment (pull the metadata from Salesforce into Git).
+# Flow in an environment (sync metadata from Salesforce into Git)
 
 name: Flow in an environment
+
 on:
-  # This action is always manually executed.
+  # This workflow is always manually executed.
   workflow_dispatch:
     inputs:
       environmentName:
-        description: >
-          Name of environment to flow in.
-
-          Make sure to enter the name of an environment that you have already created.
+        description: "Name of environment to flow in:"
         required: true
       commitMessage:
-        description: >
-          Commit message.
-        required: false        
-
-# The env:flowin command needs to be able to push changes back to the repo.
-permissions:
-  contents: write  
+        description: "Commit message (leave empty to use a default message):"
+        required: false
 
 jobs:
   flow-in:
-    name: "Flow Environment In"
-    runs-on: ubuntu-latest    
-    container: 
-      image: orgflow/cli:latest
-    env:
-      ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.
-      ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}      
-      ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }}
-      SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
-      SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }}
-    
-    steps:
-      # Verify input:
-      - name: Verify stack name
-        id: verifyStackName
-        if: ${{ always() && env.ORGFLOW_STACKNAME == '' }}
-        run: |
-          echo 'Repository secret ORGFLOW_STACKNAME has not been set. See the readme for more details.'
-          #exit 1
-      - name: Verify license key
-        id: verifyLicenseKey
-        if: ${{ always() && env.ORGFLOW_LICENSEKEY == '' }}
-        run: |
-          echo 'Repository secret ORGFLOW_LICENSEKEY has not been set. See the readme for more details.'
-          exit 
-      - name: Verify Salesforce username
-        id: verifySalesforceUsername
-        if: ${{always() && env.SALESFORCE_USERNAME == '' }}
-        run: |
-          echo 'Repository secret SALESFORCE_USERNAME has not been set. See the readme for more details.'
-          exit 1
-      - name: Verify Salesforce password
-        id: verifySalesforcePassword
-        if: ${{always() && env.SALESFORCE_PASSWORD == '' }}
-        run: |
-          echo 'Repository secret SALESFORCE_PASSWORD has not been set. See the readme for more details.'
-          exit 1
-          
-      # Configure Git:
-      - uses: orgflow-actions/configure-git@v0.4
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
+    name: Flow environment in
+    runs-on: ubuntu-latest
 
-      # Configure auth:
-      - uses: orgflow-actions/set-salesforce-auth@v0.2
-        with:
-          username: ${{ secrets.SALESFORCE_USERNAME }}
-          password: ${{ secrets.SALESFORCE_PASSWORD }}   
-          
-      # Run OrgFlow command:
-      - name: env:flowin
+    steps:
+      # Verify secrets:
+      - name: Verify secrets
         run: |
-          orgflow env:flowin -e="${{ github.event.inputs.environmentName }}" -m="${{ github.event.inputs.commitMessage }}"      
-      
-      # Publish diagnostic bundles to artifacts (if any):
-      - name: Publish diagnostic bundle as artifact
-        uses: actions/upload-artifact@v2
-        if: always()
+          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.SALESFORCE_USERNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_USERNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.SALESFORCE_PASSWORD }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_PASSWORD has not been set. See the Readme for more details." && exit 1; fi;
+
+      # Install and configure OrgFlow:
+      - name: Install OrgFlow
+        uses: orgflow-actions/setup@v1
         with:
-          name: Diagnostic Bundles
-          path: |
-            /tmp/OrgFlow_Diagnostics_*.zip
-          retention-days: 3
-          if-no-files-found: ignore
+          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
+          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
+          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
+          git-username: ${{ github.actor }}
+          git-password: ${{ secrets.GITHUB_TOKEN }}
+          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
+        env:
+          ORGFLOW_ACCEPTEULA: "true"
+
+      # Run OrgFlow command to flow in environment:
+      - name: Run env:flowin
+        run: |
+          orgflow env:flowin --environment="${{ github.event.inputs.environmentName }}" --message="${{ github.event.inputs.commitMessage }}"
diff --git a/.github/workflows/env-flowout.yml b/.github/workflows/env-flowout.yml
--- a/.github/workflows/env-flowout.yml
+++ b/.github/workflows/env-flowout.yml
@@ -1,98 +1,50 @@
-# Flow out an environment (push the metadata from Git into Salesforce).
+# Flow out an environment (sync metadata from Git to Salesforce)
 
 name: Flow out an environment
+
 on:
-  push:
-    branches-ignore: [ main ] # Remove this line to enable deployments to production. Note- we assume that the production environment is backed by a branch called `main`; if this is not the case, then you'll need to update this value.
-        
+  # This workflow is always manually executed.
+  workflow_dispatch:
+    inputs:
+      environmentName:
+        description: "Name of environment to flow out:"
+        required: true
+
 jobs:
   flow-out:
-    name: "Flow Environment Out"
-    runs-on: ubuntu-latest    
-    container: 
-      image: orgflow/cli:latest
-    env:
-      ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.
-      ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}      
-      ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }} 
-      SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
-      SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }}   
-          
+    name: Flow environment out
+    runs-on: ubuntu-latest
+
     steps:
-      # Verify input:
-      - name: Verify stack name
-        id: verifyStackName
-        if: ${{ always() && env.ORGFLOW_STACKNAME == '' }}
+      # Verify secrets:
+      - name: Verify secrets
         run: |
-          echo 'Repository secret ORGFLOW_STACKNAME has not been set. See the readme for more details.'
-          #exit 1
-      - name: Verify license key
-        id: verifyLicenseKey
-        if: ${{ always() && env.ORGFLOW_LICENSEKEY == '' }}
-        run: |
-          echo 'Repository secret ORGFLOW_LICENSEKEY has not been set. See the readme for more details.'
-          exit 
-      - name: Verify Salesforce username
-        id: verifySalesforceUsername
-        if: ${{always() && env.SALESFORCE_USERNAME == '' }}
-        run: |
-          echo 'Repository secret SALESFORCE_USERNAME has not been set. See the readme for more details.'
-          exit 1
-      - name: Verify Salesforce password
-        id: verifySalesforcePassword
-        if: ${{always() && env.SALESFORCE_PASSWORD == '' }}
-        run: |
-          echo 'Repository secret SALESFORCE_PASSWORD has not been set. See the readme for more details.'
-          exit 1
-          
-      # Get the branch name that triggered this action, and format it in a way that OrgFlow can understand it:
-      - id: get-branch
-        name: Get branch name
-        run: echo "BRANCHNAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
-          
-      # Use jq to scan the output from env:list to retrieve the environment name based on the branch:
-      - id: get-environment
-        name: Get OrgFlow environment from branch name
-        run: echo ORGFLOW_ENVIRONMENT=`orgflow env:list --output=json | jq '.[] | select(.git.branch == env.BRANCHNAME) | .name'` >> $GITHUB_ENV
+          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.SALESFORCE_USERNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_USERNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.SALESFORCE_PASSWORD }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_PASSWORD has not been set. See the Readme for more details." && exit 1; fi;
 
-      # Print a message if there is no environment for this branch:
-      - id: environment-check
-        name: Print if this branch is not related to an environment
-        if: ${{ env.ORGFLOW_ENVIRONMENT == '' }}
-        run: echo "Branch '$BRANCHNAME' does not belong to any environment on this stack."      
-          
-      # Configure Git:
-      - uses: orgflow-actions/configure-git@v0.4
-        if: ${{ env.ORGFLOW_ENVIRONMENT != '' }}
+      # Install and configure OrgFlow:
+      - name: Install OrgFlow
+        uses: orgflow-actions/setup@v1
         with:
-          token: ${{ secrets.GITHUB_TOKEN }}
+          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
+          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
+          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
+          git-username: ${{ github.actor }}
+          git-password: ${{ secrets.GITHUB_TOKEN }}
+          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
+        env:
+          ORGFLOW_ACCEPTEULA: "true"
 
-      # Configure auth:
-      - uses: orgflow-actions/set-salesforce-auth@v0.2
-        if: ${{ env.ORGFLOW_ENVIRONMENT != '' }}
-        with:
-          username: ${{ secrets.SALESFORCE_USERNAME }}
-          password: ${{ secrets.SALESFORCE_PASSWORD }}        
-          
-      # It's good practice flow in before you flow out, to avoid loss of data in the Salesforce org:
-      - name: env:flowin
-        if: ${{ env.ORGFLOW_ENVIRONMENT != '' }}
+      # Run OrgFlow command to flow in environment:
+      # It's good practice to flow in before you flow out, to avoid loss of data in the Salesforce org:
+      - name: Run env:flowin
         run: |
-          orgflow env:flowin -e="$ORGFLOW_ENVIRONMENT"
-          
+          orgflow env:flowin --environment="${{ github.event.inputs.environmentName }}"
+
+      # Run OrgFlow command to flow out environment:
       # Flow out to deploy the changes from Git to Salesforce:
-      - name: env:flowout
-        if: ${{ env.ORGFLOW_ENVIRONMENT != '' }}
+      - name: Run env:flowout
         run: |
-          orgflow env:flowout -e="$ORGFLOW_ENVIRONMENT" --checkOnly      
-      
-      # Publish diagnostic bundles to artifacts (if any):
-      - name: Publish diagnostic bundle as artifact
-        uses: actions/upload-artifact@v2
-        if: always()
-        with:
-          name: Diagnostic Bundles
-          path: |
-            /tmp/OrgFlow_Diagnostics_*.zip
-          retention-days: 3
-          if-no-files-found: ignore
+          orgflow env:flowout --environment="${{ github.event.inputs.environmentName }}"
diff --git a/.github/workflows/env-test.yml b/.github/workflows/env-test.yml
--- a/.github/workflows/env-test.yml
+++ b/.github/workflows/env-test.yml
@@ -1,98 +1,54 @@
-# Run the tests in the Salesforce org for a particular environment, and then publish the results.
+# Run tests in an environment and publish the results
 
-name: Run tests
+name: Run tests in an environment
+
 on:
-  # This action must be manually executed.
+  # This workflow is always manually executed.
   workflow_dispatch:
     inputs:
       environmentName:
-        description: 'Name of the environment to run tests for.'
+        description: "Name of the environment to run tests in:"
         required: true
 
 jobs:
   env-test:
-    name: Run Tests
+    name: Run tests in environment
     runs-on: ubuntu-latest    
-    container: 
-      image: orgflow/cli:latest
-    env:
-      ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.
-      ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}      
-      ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }} 
-      SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
-      SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }}  
 
     steps:
-      # Verify input:
-      - name: Verify stack name
-        id: verifyStackName
-        if: ${{ always() && env.ORGFLOW_STACKNAME == '' }}
+      # Verify secrets:
+      - name: Verify secrets
         run: |
-          echo 'Repository secret ORGFLOW_STACKNAME has not been set. See the readme for more details.'
-          #exit 1
-      - name: Verify license key
-        id: verifyLicenseKey
-        if: ${{ always() && env.ORGFLOW_LICENSEKEY == '' }}
-        run: |
-          echo 'Repository secret ORGFLOW_LICENSEKEY has not been set. See the readme for more details.'
-          exit 
-      - name: Verify Salesforce username
-        id: verifySalesforceUsername
-        if: ${{always() && env.SALESFORCE_USERNAME == '' }}
-        run: |
-          echo 'Repository secret SALESFORCE_USERNAME has not been set. See the readme for more details.'
-          exit 1
-      - name: Verify Salesforce password
-        id: verifySalesforcePassword
-        if: ${{always() && env.SALESFORCE_PASSWORD == '' }}
-        run: |
-          echo 'Repository secret SALESFORCE_PASSWORD has not been set. See the readme for more details.'
-          exit 1
-          
-      # Add the environment name to the environment variables so that jq can use it:
-      - id: get-branch
-        name: Get branch name
-        run: echo "ORGFLOW_ENVIRONMENT=${{ github.event.inputs.environmentName }}" >> $GITHUB_ENV
-          
-      # Use jq to scan the output from env:list to retrieve the environment name based on the branch:
-      - id: get-sha
-        name: Get commit hash for environment
-        run: echo ORGFLOW_SHA=`orgflow env:list --output=json | jq '.[] | select(.name == env.ORGFLOW_ENVIRONMENT) | .git.parityHash'` >> $GITHUB_ENV
+          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.SALESFORCE_USERNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_USERNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.SALESFORCE_PASSWORD }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_PASSWORD has not been set. See the Readme for more details." && exit 1; fi;
 
-      # The test results publisher requires that the repository is checked out:
-      - uses: actions/checkout@v2 
-        name: Checkout at hash for environment
-        # with:
-        #   ref: $ORGFLOW_SHA
+      # TODO: Is this still needed?
+      # The test results publisher requires that the repository be checked out:
+      # - uses: actions/checkout@v2 
+      #   name: Checkout at hash for environment
 
-      # Configure auth:
-      - uses: orgflow-actions/set-salesforce-auth@v0.2
+      # Install and configure OrgFlow:
+      - name: Install OrgFlow
+        uses: orgflow-actions/setup@v1
         with:
-          username: ${{ secrets.SALESFORCE_USERNAME }}
-          password: ${{ secrets.SALESFORCE_PASSWORD }} 
+          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
+          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
+          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
+          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
+        env:
+          ORGFLOW_ACCEPTEULA: "true"
       
-      # Run OrgFlow command:
-      - name: env:test
-        run: orgflow env:test -e="${{ github.event.inputs.environmentName }}" --jUnitTo="${{ env.RUNNER_TEMP }}junit.xml" -c="Test_OrderPath_CC"
+      # Run OrgFlow command to execute tests in Salesforce:
+      - name: Run env:test
+        run: orgflow env:test --environment="${{ github.event.inputs.environmentName }}" --jUnitTo="${{ env.RUNNER_TEMP }}junit.xml"
 
       # Publish the test results using an action from the marketplace:
       - name: Generate test report
         uses: dorny/test-reporter@v1
-        if: always()
+        if: always() # Even if some tests failed
         with:
-          name: Test Results
+          name: Test results
           path: ${{ env.RUNNER_TEMP }}junit.xml
           reporter: java-junit
-      
-      # Publish diagnostic bundles to artifacts (if any):
-      - name: Publish diagnostic bundle as artifact
-        uses: actions/upload-artifact@v2
-        if: always()
-        with:
-          name: Diagnostic Bundles
-          path: |
-            /tmp/OrgFlow_Diagnostics_*.zip
-            ${{ env.RUNNER_TEMP }}junit.xml
-          retention-days: 3
-          if-no-files-found: ignore
-      
diff --git a/.github/workflows/env-unlock.yml b/.github/workflows/env-unlock.yml
--- a/.github/workflows/env-unlock.yml
+++ b/.github/workflows/env-unlock.yml
@@ -1,53 +1,36 @@
-# Unlock an environment in the event that it gets into a state where it is permanently locked.
-# TIP- this can happen if a GitHub workflow gets cancelled, as the cancellation token does not get correctly forwarded to OrgFlow, so OrgFlow will not unlock the environment before exiting.
+# Unlock an environment (in case it's left locked)
 
 name: Unlock an environment
 
 on:
-  # This action is always manually executed.
+  # This workflow is always manually executed.
   workflow_dispatch:
     inputs:
       environmentName:
-        description: 'Name of environment to unlock.'
+        description: "Name of environment to unlock:"
         required: true
 
 jobs:
   env-unlock:
-    name: Unlock Environment
-    runs-on: ubuntu-latest    
-    container: 
-      image: orgflow/cli:latest
-    env:
-      ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.
-      ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}      
-      ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }}
+    name: Unlock environment
+    runs-on: ubuntu-latest
 
     steps:
-      # Verify input:
-      - name: Verify stack name
-        id: verifyStackName
-        if: ${{ always() && env.ORGFLOW_STACKNAME == '' }}
+      # Verify secrets:
+      - name: Verify secrets
         run: |
-          echo 'Repository secret ORGFLOW_STACKNAME has not been set. See the readme for more details.'
-          #exit 1
-      - name: Verify license key
-        id: verifyLicenseKey
-        if: ${{ always() && env.ORGFLOW_LICENSEKEY == '' }}
-        run: |
-          echo 'Repository secret ORGFLOW_LICENSEKEY has not been set. See the readme for more details.'
-          exit 
-      
-      # Run OrgFlow command:
-      - name: env:unlock
-        run: orgflow env:unlock -e="${{ github.event.inputs.environmentName }}"      
-      
-      # Publish diagnostic bundles to artifacts (if any):
-      - name: Publish diagnostic bundle as artifact
-        uses: actions/upload-artifact@v2
-        if: always()
+          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;
+
+      # Install and configure OrgFlow:
+      - name: Install OrgFlow
+        uses: orgflow-actions/setup@v1
         with:
-          name: Diagnostic Bundles
-          path: |
-            /tmp/OrgFlow_Diagnostics_*.zip
-          retention-days: 3
-          if-no-files-found: ignore
+          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
+          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
+        env:
+          ORGFLOW_ACCEPTEULA: "true"
+
+      # Run OrgFlow command to unlock environment:
+      - name: env:unlock
+        run: orgflow env:unlock --environment="${{ github.event.inputs.environmentName }}"
diff --git a/.github/workflows/stack-create.yml b/.github/workflows/stack-create.yml
--- a/.github/workflows/stack-create.yml
+++ b/.github/workflows/stack-create.yml
@@ -1,72 +1,62 @@
-# Creates a new OrgFlow stack for the current repo. In OrgFlow, a stack is a collection of environments, and maps to a single git repo. Your stack will get linked to this repo, and any environments that you create will be backed by branches within this repo.
-# NOTE: for simplicity, we assume some input- we'll name your production environment 'Production', and we'll commit all its metadata to a branch called 'main'.
+# Create your OrgFlow stack based on configured secrets in your repository
+
 name: Create the stack
 
 on:
-  # This action is always manually executed.
+  # This workflow is always manually executed.
   workflow_dispatch:
-
-# The stack:create command needs to be able to push changes back to the repo.
-permissions:
-  contents: write  
 
 jobs:
   stack-create:
-    name: Create Stack
-    runs-on: ubuntu-latest    
+    name: Create stack
+    runs-on: ubuntu-latest
+    # Run in OrgFlow container to avoid having to download and install:
+    # NOTE: Normally we'd use the 'orgflow-actions/setup' action, but that action depends on the stack having already been created.
     container: 
       image: orgflow/cli:latest
-    env:
-      ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.    
-      ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }}
-      ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}
-      SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
-      SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }}
-      
+      env:
+        ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.    
+        ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }}
+        ORGFLOW_OUTPUTTEMPLATE_WARNING: "::warning title=OrgFlow Warning::$$msg$$"
+        ORGFLOW_OUTPUTTEMPLATE_ERROR: "::error title=OrgFlow Error::$$msg$$"
+
     steps:
-      # Verify input:
-      - name: Verify stack name
-        id: verifyStackName
-        if: ${{always() && env.ORGFLOW_STACKNAME == '' }}
+      # Verify secrets:
+      - name: Verify secrets
         run: |
-          echo 'Repository secret ORGFLOW_STACKNAME has not been set. See the readme for more details.
-          exit 1
-      - name: Verify license key
-        id: verifyLicenseKey
-        if: ${{always() && env.ORGFLOW_LICENSEKEY == '' }}
-        run: |
-          echo 'Repository secret ORGFLOW_LICENSEKEY has not been set. See the readme for more details.
-          exit 1
-      - name: Verify Salesforce username
-        id: verifySalesforceUsername
-        if: ${{always() && env.SALESFORCE_USERNAME == '' }}
-        run: |
-          echo 'Repository secret SALESFORCE_USERNAME has not been set. See the readme for more details.'
-          exit 1
-      - name: Verify Salesforce password
-        id: verifySalesforcePassword
-        if: ${{always() && env.SALESFORCE_PASSWORD == '' }}
-        run: |
-          echo 'Repository secret SALESFORCE_PASSWORD has not been set. See the readme for more details.'
-          exit 1
-      
+          # echo "::notice title=ORGFLOW_STACKNAME::${{ secrets.ORGFLOW_STACKNAME }}"
+          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.SALESFORCE_USERNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_USERNAME has not been set. See the Readme for more details." && exit 1; fi;
+          if ["${{ secrets.SALESFORCE_PASSWORD }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_PASSWORD has not been set. See the Readme for more details." && exit 1; fi;
+
       # Configure Git:
-      - uses: orgflow-actions/configure-git@v0.3
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          
-      # Run OrgFlow command:
-      - name: stack:create
+      # NOTE: Normally the 'orgflow-actions/setup' action would do this, but that action depends on the stack having already been created.
+      - name: Configure Git
         run: |
-          orgflow stack:create -n="${{ secrets.ORGFLOW_STACKNAME }}" -r="$GITHUB_SERVER_URL/${{ github.repository }}.git" -b=main -u="${{ secrets.SALESFORCE_USERNAME }}" -p="${{ secrets.SALESFORCE_PASSWORD }}" -i=UseExisting -e=Production      
-      
-      # Publish diagnostic bundles to artifacts (if any):
-      - name: Publish diagnostic bundle as artifact
+          # Set the username for the repo:
+          git config --global credential.$GITHUB_SERVER_URL.username ${{ github.actor }}         
+          # Create a script for ASKPASS to run to get the access token:
+          echo 'echo ${{ secrets.GITHUB_TOKEN }}' > $HOME/.git-askpass
+          chmod +x $HOME/.git-askpass
+          # Register the script with ASKPASS:
+          echo "GIT_ASKPASS=$HOME/.git-askpass" >> $GITHUB_ENV
+          # Set default values for commit signatures:
+          git config --global user.email "defaultcommitter@orgflow.io"
+          git config --global user.name "OrgFlow Default Committer"
+
+      # Run OrgFlow command to create stack:
+      - name: Run stack:create
+        run: |
+          orgflow stack:create --name="${{ secrets.ORGFLOW_STACKNAME }}" --gitRepoUrl="$GITHUB_SERVER_URL/${{ github.repository }}.git" --gitBranch=production --username="${{ secrets.SALESFORCE_USERNAME }}" --password="${{ secrets.SALESFORCE_PASSWORD }}" --productionEnvironmentName=Production
+
+      # Publish any diagnostic bundles as an artifact:
+      # NOTE: Normally the 'orgflow-actions/setup' action would do this, but that action depends on the stack having already been created.
+      - name: Publish diagnostic bundle
         uses: actions/upload-artifact@v2
         if: always()
         with:
-          name: Diagnostic Bundles
-          path: |
-            /tmp/OrgFlow_Diagnostics_*.zip
+          name: orgflow_diag_${{ github.job }}_${{ github.run_attempt }}
+          path: /tmp/OrgFlow_Diagnostics_*.zip
           retention-days: 3
           if-no-files-found: ignore
